// <auto-generated />
using core_classe.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace coreclasse.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20180313141155_Migracio Inicial")]
    partial class MigracioInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("core_classe.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cognoms")
                        .HasMaxLength(150);

                    b.Property<string>("Nom")
                        .HasMaxLength(50);

                    b.Property<string>("Perfil");

                    b.HasKey("Id");

                    b.ToTable("Gent");
                });
#pragma warning restore 612, 618
        }
    }
}
