// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using net_core_webapi_select2.Models;
using System;

namespace netcorewebapiselect2.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("net_core_webapi_select2.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cognoms")
                        .HasMaxLength(150);

                    b.Property<string>("Nom")
                        .HasMaxLength(50);

                    b.Property<string>("Perfil");

                    b.HasKey("Id");

                    b.ToTable("Gent");
                });
#pragma warning restore 612, 618
        }
    }
}
